'use client';

import { useEffect, useState } from 'react';
import { FileDown } from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  AlertDialog,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from '@/components/ui/alert-dialog';
import { FormField } from '@/components/ui/form-field';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';

// Both PDF reports live behind one button: the per-department one needs a
// department picked anyway, so a dialog is the honest place for the choice.
// The preview is the real PDF, not a drawing of it — what you see is the file
// you get, because it is generated by the same route the download calls.

const METRICS: { value: string; label: string }[] = [
  { value: 'total', label: 'Загальний бал' },
  { value: '1', label: 'Розділ 1 — професійний розвиток' },
  { value: '2', label: 'Розділ 2 — навчальна діяльність' },
  { value: '3', label: 'Розділ 3 — науково-інноваційна діяльність' },
  { value: '4', label: 'Розділ 4 — організаційна діяльність' },
  { value: '5', label: 'Розділ 5 — навчально-методичне забезпечення' },
];

export function RatingPdfDialog({
  year,
  departments,
}: {
  year: number;
  departments: { id: string; name: string }[];
}) {
  const [open, setOpen] = useState(false);
  const [kind, setKind] = useState<'departments' | 'staff'>('departments');
  // Розділ 3 — те, що показують нинішні паперові звіти
  const [metric, setMetric] = useState('3');
  const [departmentId, setDepartmentId] = useState(departments[0]?.id ?? '');

  const params = new URLSearchParams({ kind, metric, year: String(year) });
  if (kind === 'staff') params.set('departmentId', departmentId);
  const href = `/api/export/rating-chart?${params.toString()}`;
  // Same file, rendered rather than saved — see the route's contentDisposition
  const inlineHref = `${href}&inline=1`;

  const ready = kind === 'departments' || departmentId !== '';

  // Rebuilding a PDF on every keystroke of the filters would hammer the server,
  // so the preview follows a beat behind the controls.
  const [previewHref, setPreviewHref] = useState(inlineHref);
  useEffect(() => {
    if (!open || !ready) return;
    const id = setTimeout(() => setPreviewHref(inlineHref), 350);
    return () => clearTimeout(id);
  }, [inlineHref, open, ready]);

  return (
    <AlertDialog open={open} onOpenChange={setOpen}>
      <AlertDialogTrigger asChild>
        <Button variant="ghost" size="sm" className="text-muted-foreground hover:text-foreground">
          <FileDown className="size-4" />
          PDF
        </Button>
      </AlertDialogTrigger>

      {/* A fixed height, not just a cap: the preview should get the room, and a
          dialog sized to its content would shrink the page to a stamp. */}
      <AlertDialogContent className="flex h-[92vh] max-h-216 w-[min(64rem,94vw)] max-w-none flex-col gap-0 overflow-hidden p-0">
        <AlertDialogHeader className="border-b px-6 py-4">
          <AlertDialogTitle>Рейтинг у PDF</AlertDialogTitle>
          <AlertDialogDescription>
            Діаграма за {year} рік — у тому ж вигляді, що й паперові звіти.
          </AlertDialogDescription>
        </AlertDialogHeader>

        <div className="flex min-h-0 flex-1 flex-col gap-4 overflow-y-auto p-5 md:flex-row">
          <div className="w-full shrink-0 space-y-4 md:w-72">
            <FormField htmlFor="pdfKind" label="Що показати">
              <Select value={kind} onValueChange={(v) => setKind(v as typeof kind)}>
                <SelectTrigger id="pdfKind" className="w-full">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="departments">Усі кафедри — середній бал</SelectItem>
                  <SelectItem value="staff">Одна кафедра — по кожному НПП</SelectItem>
                </SelectContent>
              </Select>
            </FormField>

            {kind === 'staff' && (
              <FormField htmlFor="pdfDepartment" label="Кафедра">
                <Select value={departmentId} onValueChange={setDepartmentId}>
                  <SelectTrigger id="pdfDepartment" className="w-full">
                    <SelectValue placeholder="Оберіть кафедру" />
                  </SelectTrigger>
                  <SelectContent>
                    {departments.map((d) => (
                      <SelectItem key={d.id} value={d.id}>
                        {d.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </FormField>
            )}

            <FormField
              htmlFor="pdfMetric"
              label="Показник"
              description={
                kind === 'staff'
                  ? 'Друкується поряд із загальною сумою балів кожного НПП'
                  : 'За ним кафедри шикуються у рейтингу'
              }
            >
              <Select value={metric} onValueChange={setMetric}>
                <SelectTrigger id="pdfMetric" className="w-full">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {METRICS.map((m) => (
                    <SelectItem key={m.value} value={m.value}>
                      {m.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </FormField>
          </div>

          {/* A4 upright, so the preview keeps the proportions of the printed page */}
          <div className="min-h-0 flex-1 overflow-hidden rounded-lg border bg-muted/30">
            {ready ? (
              <iframe
                key={previewHref}
                src={`${previewHref}#toolbar=0&navpanes=0&view=FitH`}
                title="Попередній перегляд звіту"
                className="h-full min-h-104 w-full"
              />
            ) : (
              <p className="p-8 text-center text-sm text-muted-foreground">
                Оберіть кафедру, щоб побачити діаграму.
              </p>
            )}
          </div>
        </div>

        <AlertDialogFooter className="border-t px-6 py-4">
          <AlertDialogCancel type="button">Закрити</AlertDialogCancel>
          <Button asChild disabled={!ready}>
            <a href={href} download>
              Завантажити
            </a>
          </Button>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  );
}
